// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfkjhyhxtvwtdijhoaxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBma2poeWh4dHZ3dGRpamhvYXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2MTQ0NDksImV4cCI6MjA0ODE5MDQ0OX0._HeY4NIrYErFHes9k9-O3Y-j2LyI3JAcy2-8wDGnjOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);