// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwadjvggjecrmzhmbpub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3YWRqdmdnamVjcm16aG1icHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODEyNTUsImV4cCI6MjA1Njk1NzI1NX0.q53FaqYMU9ZSHL_Hv7MGWS7wZxYg57CWRqpp44NwRQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);